### ISSUE TITLE
core-4.0.0: fetch/git.py broken on SRC_URI without branch/tag/commit

### ISSUE THREAD

**Issue by mikaelj** [oe-lite/core#32]
Invalid URI: cannot mix commit, tag and branch parameters:
git://git@192.168.0.6/lpc21isp.git

In the past, that always fetched HEAD. Now I can no longer fetch HEAD.

Workaround or possible fix.

    commit fc81d53c830e9a99d96eb0bef1ce885029dd1d5f
    Author: Mikael Jansson <mikael.jansson@tlabwest.se>
    Date:   Thu Aug 20 14:16:08 2015 +0200

        WORKAROUND: fix not having a branch specified.

    diff --git a/lib/oelite/fetch/git.py b/lib/oelite/fetch/git.py
    index 51844e7..7d5c155 100644
    --- a/lib/oelite/fetch/git.py
    +++ b/lib/oelite/fetch/git.py
    @@ -67,6 +67,7 @@ class GitFetcher():
             i = bool(self.commit) + bool(self.tag) + bool(self.branch)
             if i == 0:
                 self.branch = "HEAD"
    +            i = 1
                 if self.is_local and not hasattr(self, 'dirty'):
                     self.dirty = True
             if "dirty" in uri.params:

**Comment by esben** [comment]
Looks good.  Could you make a PR with this?

**Comment by mikaelj** [comment]
https://github.com/oe-lite/core/pull/36
