### ISSUE TITLE
[gcc-4.8.2 core-4.x] Generated kernel crashes constantly, broken gcc?

### ISSUE THREAD

**Issue by mikaelj** [oe-lite/core#38]
I get this problem all the time after upgrading to core-4.0 from core-3.5.x. Target platform imx6 soft-float.

https://lkml.org/lkml/2015/3/13/318

From what I understand in that bug report, GCC does not always work. In their case, they're using 4.8.2, which is the same we're using.  It leads me to think that their problem and mine is the same.

**Comment by esben** [comment]
Have you seen any hints about which GCC versions have this fixed?  Could an upgrade to 4.8.5 resolve it?

The OE-lite/core 4 branch is fixed on gcc 4.8.  The current OE-lite/core master is currently on 4.9, but I hope to upgrade to gcc 5 (but gave up on 5.1, hoping that 5.2 is better).

**Comment by mikaelj** [comment]
I'm just building 4.9.3 to see if that solves the problem.  If it does, I'll try a later 4.8.x version, else I'll continue forward.

**Comment by mikaelj** [comment]
kimrhh says anything >4.8.2 is not affected.

**Comment by mikaelj** [comment]
I've changed my mind and I'm trying out 4.8.5 instead.   Do we want to create a maintenance branch for 4.0 and then release off that?

**Comment by esben** [comment]
Let's fix this by upgrading GCC to 4.8.5 (see #42).
