### ISSUE TITLE
bake.run() is trying to expand variables in uncommented lines

### ISSUE THREAD

**Issue by krevsbech** [oe-lite/core#81]
When using '#' comments in recipe files bake.run is still trying to expand variables, and fails if this is not possible.

*Reproduce*
In e.g. do_install() insert a expandable on a comment line: 
do_install () {
 # ${FOO}
}
Will result in:
CRITICAL: bake failed: Exception: Cannot expand variable ${HEST}
While running bake.run()

**Comment by esben** [comment]
True, but avoiding that would require a complete shell parser.

Fx.

```sh
do_install() {
   FOOBAR="
# ${FOO}
# ${BAR}
"
...
}
```

Requires expansion of ${FOO} and ${BAR}.

And I don't think the benefits outweights the cost of including a shell parser.

What do you propose we should do?

**Comment by krevsbech** [comment]
As you point out it is probably not worth fixing, as the impact is minor compared to the cost of implementing a full fleshed shell parser. 
I'll close the issue. 
Thanks.
